// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Item.Domains.Item.Certificates
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id:asc")]
        #pragma warning disable CS1591
        IdAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "id:desc")]
        #pragma warning disable CS1591
        IdDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "common_name:asc")]
        #pragma warning disable CS1591
        Common_nameAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "common_name:desc")]
        #pragma warning disable CS1591
        Common_nameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "expiration:asc")]
        #pragma warning disable CS1591
        ExpirationAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "expiration:desc")]
        #pragma warning disable CS1591
        ExpirationDesc,
        #pragma warning restore CS1591
    }
}
