// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DomainRegistration_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "registering")]
        #pragma warning disable CS1591
        Registering,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered")]
        #pragma warning disable CS1591
        Registered,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
