// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QueryDnsAnalyticsGroupingsParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
        [EnumMember(Value = "volume")]
        #pragma warning disable CS1591
        Volume,
        #pragma warning restore CS1591
        [EnumMember(Value = "zone_name")]
        #pragma warning disable CS1591
        ZoneName,
        #pragma warning restore CS1591
    }
}
