// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortCharges
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invoiced:asc")]
        #pragma warning disable CS1591
        InvoicedColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "invoiced:desc")]
        #pragma warning disable CS1591
        InvoicedColonDesc,
        #pragma warning restore CS1591
    }
}
