// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortServices
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id:asc")]
        #pragma warning disable CS1591
        IdColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "id:desc")]
        #pragma warning disable CS1591
        IdColonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "sid:asc")]
        #pragma warning disable CS1591
        SidColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "sid:desc")]
        #pragma warning disable CS1591
        SidColonDesc,
        #pragma warning restore CS1591
    }
}
