// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortCertificates
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id:asc")]
        #pragma warning disable CS1591
        IdColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "id:desc")]
        #pragma warning disable CS1591
        IdColonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "common_name:asc")]
        #pragma warning disable CS1591
        CommonNameColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "common_name:desc")]
        #pragma warning disable CS1591
        CommonNameColonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "expiration:asc")]
        #pragma warning disable CS1591
        ExpirationColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "expiration:desc")]
        #pragma warning disable CS1591
        ExpirationColonDesc,
        #pragma warning restore CS1591
    }
}
