// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortContacts
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id:asc")]
        #pragma warning disable CS1591
        IdColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "id:desc")]
        #pragma warning disable CS1591
        IdColonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "label:asc")]
        #pragma warning disable CS1591
        LabelColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "label:desc")]
        #pragma warning disable CS1591
        LabelColonDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "email:asc")]
        #pragma warning disable CS1591
        EmailColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "email:desc")]
        #pragma warning disable CS1591
        EmailColonDesc,
        #pragma warning restore CS1591
    }
}
