// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SortTlDs
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "tld:asc")]
        #pragma warning disable CS1591
        TldColonAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "tld:desc")]
        #pragma warning disable CS1591
        TldColonDesc,
        #pragma warning restore CS1591
    }
}
