// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    /// <summary>The type of DNS record. Supported DNS record types are listed below. Note that some record types may only be available on specific plans.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ZoneRecordType
    {
        [EnumMember(Value = "A")]
        #pragma warning disable CS1591
        A,
        #pragma warning restore CS1591
        [EnumMember(Value = "AAAA")]
        #pragma warning disable CS1591
        Aaaa,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALIAS")]
        #pragma warning disable CS1591
        Alias,
        #pragma warning restore CS1591
        [EnumMember(Value = "CAA")]
        #pragma warning disable CS1591
        Caa,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNAME")]
        #pragma warning disable CS1591
        Cname,
        #pragma warning restore CS1591
        [EnumMember(Value = "DNSKEY")]
        #pragma warning disable CS1591
        Dnskey,
        #pragma warning restore CS1591
        [EnumMember(Value = "DS")]
        #pragma warning disable CS1591
        Ds,
        #pragma warning restore CS1591
        [EnumMember(Value = "HINFO")]
        #pragma warning disable CS1591
        Hinfo,
        #pragma warning restore CS1591
        [EnumMember(Value = "MX")]
        #pragma warning disable CS1591
        Mx,
        #pragma warning restore CS1591
        [EnumMember(Value = "NAPTR")]
        #pragma warning disable CS1591
        Naptr,
        #pragma warning restore CS1591
        [EnumMember(Value = "NS")]
        #pragma warning disable CS1591
        Ns,
        #pragma warning restore CS1591
        [EnumMember(Value = "POOL")]
        #pragma warning disable CS1591
        Pool,
        #pragma warning restore CS1591
        [EnumMember(Value = "PTR")]
        #pragma warning disable CS1591
        Ptr,
        #pragma warning restore CS1591
        [EnumMember(Value = "SOA")]
        #pragma warning disable CS1591
        Soa,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPF")]
        #pragma warning disable CS1591
        Spf,
        #pragma warning restore CS1591
        [EnumMember(Value = "SRV")]
        #pragma warning disable CS1591
        Srv,
        #pragma warning restore CS1591
        [EnumMember(Value = "SSHFP")]
        #pragma warning disable CS1591
        Sshfp,
        #pragma warning restore CS1591
        [EnumMember(Value = "TXT")]
        #pragma warning disable CS1591
        Txt,
        #pragma warning restore CS1591
        [EnumMember(Value = "URL")]
        #pragma warning disable CS1591
        Url,
        #pragma warning restore CS1591
    }
}
