// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Item.Domains.Item.Email_forwards
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "id:asc")]
        #pragma warning disable CS1591
        IdAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "id:desc")]
        #pragma warning disable CS1591
        IdDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "from:asc")]
        #pragma warning disable CS1591
        FromAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "from:desc")]
        #pragma warning disable CS1591
        FromDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "to:asc")]
        #pragma warning disable CS1591
        ToAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "to:desc")]
        #pragma warning disable CS1591
        ToDesc,
        #pragma warning restore CS1591
    }
}
