// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Item.Billing.Charges
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invoiced:asc")]
        #pragma warning disable CS1591
        InvoicedAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "invoiced:desc")]
        #pragma warning disable CS1591
        InvoicedDesc,
        #pragma warning restore CS1591
    }
}
