// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Item.Secondary_dns.Primaries.Item.Unlink
{
    [Obsolete("This class is obsolete. Use UnlinkPutResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UnlinkResponse : global::Soenneker.DNSimple.OpenApiClient.Item.Secondary_dns.Primaries.Item.Unlink.UnlinkPutResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DNSimple.OpenApiClient.Item.Secondary_dns.Primaries.Item.Unlink.UnlinkResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.DNSimple.OpenApiClient.Item.Secondary_dns.Primaries.Item.Unlink.UnlinkResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DNSimple.OpenApiClient.Item.Secondary_dns.Primaries.Item.Unlink.UnlinkResponse();
        }
    }
}
#pragma warning restore CS0618
