// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Certificate_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "new")]
        #pragma warning disable CS1591
        New,
        #pragma warning restore CS1591
        [EnumMember(Value = "purchased")]
        #pragma warning disable CS1591
        Purchased,
        #pragma warning restore CS1591
        [EnumMember(Value = "configured")]
        #pragma warning disable CS1591
        Configured,
        #pragma warning restore CS1591
        [EnumMember(Value = "submitted")]
        #pragma warning disable CS1591
        Submitted,
        #pragma warning restore CS1591
        [EnumMember(Value = "issued")]
        #pragma warning disable CS1591
        Issued,
        #pragma warning restore CS1591
        [EnumMember(Value = "rejected")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "refunded")]
        #pragma warning disable CS1591
        Refunded,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
        [EnumMember(Value = "requesting")]
        #pragma warning disable CS1591
        Requesting,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
    }
}
