// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Domain_state
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "hosted")]
        #pragma warning disable CS1591
        Hosted,
        #pragma warning restore CS1591
        [EnumMember(Value = "registered")]
        #pragma warning disable CS1591
        Registered,
        #pragma warning restore CS1591
        [EnumMember(Value = "expired")]
        #pragma warning disable CS1591
        Expired,
        #pragma warning restore CS1591
    }
}
