// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.DNSimple.OpenApiClient.Accounts;
using Soenneker.DNSimple.OpenApiClient.Item;
using Soenneker.DNSimple.OpenApiClient.Oauth;
using Soenneker.DNSimple.OpenApiClient.Services;
using Soenneker.DNSimple.OpenApiClient.Tlds;
using Soenneker.DNSimple.OpenApiClient.Whoami;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.DNSimple.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DNSimpleOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The accounts property</summary>
        public global::Soenneker.DNSimple.OpenApiClient.Accounts.AccountsRequestBuilder Accounts
        {
            get => new global::Soenneker.DNSimple.OpenApiClient.Accounts.AccountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The oauth property</summary>
        public global::Soenneker.DNSimple.OpenApiClient.Oauth.OauthRequestBuilder Oauth
        {
            get => new global::Soenneker.DNSimple.OpenApiClient.Oauth.OauthRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The services property</summary>
        public global::Soenneker.DNSimple.OpenApiClient.Services.ServicesRequestBuilder Services
        {
            get => new global::Soenneker.DNSimple.OpenApiClient.Services.ServicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tlds property</summary>
        public global::Soenneker.DNSimple.OpenApiClient.Tlds.TldsRequestBuilder Tlds
        {
            get => new global::Soenneker.DNSimple.OpenApiClient.Tlds.TldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The whoami property</summary>
        public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiRequestBuilder Whoami
        {
            get => new global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the Soenneker.DNSimple.OpenApiClient.item collection</summary>
        /// <param name="position">The account id</param>
        /// <returns>A <see cref="global::Soenneker.DNSimple.OpenApiClient.Item.WithAccountItemRequestBuilder"/></returns>
        public global::Soenneker.DNSimple.OpenApiClient.Item.WithAccountItemRequestBuilder this[int position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("account", position);
                return new global::Soenneker.DNSimple.OpenApiClient.Item.WithAccountItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DNSimple.OpenApiClient.DNSimpleOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DNSimpleOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.dnsimple.com/v2";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
