// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.DNSimple.OpenApiClient.Whoami
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class WhoamiGetResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data Data { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse"/> and sets the default values.
        /// </summary>
        public WhoamiGetResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data>(global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data>("data", Data);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1"/>, <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WhoamiGetResponse_data : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1? WhoamiGetResponseDataMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1 WhoamiGetResponseDataMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2? WhoamiGetResponseDataMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2 WhoamiGetResponseDataMember2 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse.WhoamiGetResponse_data();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WhoamiGetResponseDataMember1 = new global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.WhoamiGetResponseDataMember2 = new global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(WhoamiGetResponseDataMember1 != null)
                {
                    return WhoamiGetResponseDataMember1.GetFieldDeserializers();
                }
                else if(WhoamiGetResponseDataMember2 != null)
                {
                    return WhoamiGetResponseDataMember2.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                _ = writer ?? throw new ArgumentNullException(nameof(writer));
                if(WhoamiGetResponseDataMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember1>(null, WhoamiGetResponseDataMember1);
                }
                else if(WhoamiGetResponseDataMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.DNSimple.OpenApiClient.Whoami.WhoamiGetResponse_dataMember2>(null, WhoamiGetResponseDataMember2);
                }
            }
        }
    }
}
#pragma warning restore CS0618
